import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Provider from "./../Providers/provider";
import ScrollToTopButton from "./_component/Scroll/ScrollToTopButton";
import Footer from "./_component/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script id="theme" strategy="beforeInteractive">
          {`
            (function() {
              try {
                const theme = localStorage.getItem('darkMode');
                if(theme === 'true') document.documentElement.classList.add('dark');
              } catch(e){}
            })();
          `}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <Navbar />
          <Toaster richColors />
          {children}
          <Footer />
          <ScrollToTopButton />
        </Provider>
      </body>
    </html>
  );
}
